// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVgCia5MyH3leBEhAZsJeQV2EoLy18i-M',
    appId: '1:382033508368:web:f311d50413f3998d313295',
    messagingSenderId: '382033508368',
    projectId: 'goserve-50b3b',
    authDomain: 'goserve-50b3b.firebaseapp.com',
    storageBucket: 'goserve-50b3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5sVp6l2jb36csbDO3XwUxPx7w7342I0',
    appId: '1:382033508368:android:9ef112de2ff466c9313295',
    messagingSenderId: '382033508368',
    projectId: 'goserve-50b3b',
    storageBucket: 'goserve-50b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFR6sm28TEKy-OhJfHyba6ZgIS3Tws75s',
    appId: '1:382033508368:ios:1a31a37b07251f9d313295',
    messagingSenderId: '382033508368',
    projectId: 'goserve-50b3b',
    storageBucket: 'goserve-50b3b.firebasestorage.app',
    iosClientId: '382033508368-am6cpgl50rolb7188l2tvf88tqgi5gcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gooservee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFR6sm28TEKy-OhJfHyba6ZgIS3Tws75s',
    appId: '1:382033508368:ios:1a31a37b07251f9d313295',
    messagingSenderId: '382033508368',
    projectId: 'goserve-50b3b',
    storageBucket: 'goserve-50b3b.firebasestorage.app',
    iosClientId: '382033508368-am6cpgl50rolb7188l2tvf88tqgi5gcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gooservee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVgCia5MyH3leBEhAZsJeQV2EoLy18i-M',
    appId: '1:382033508368:web:a1ace6e1fa4dc7bc313295',
    messagingSenderId: '382033508368',
    projectId: 'goserve-50b3b',
    authDomain: 'goserve-50b3b.firebaseapp.com',
    storageBucket: 'goserve-50b3b.firebasestorage.app',
  );

}